### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alexcarous** [bateller/stripe-terminal-new#1]
For installation, the user must add "php" after "<?" on line 1 in order for index.php to function as intended, contrary to the README file which states: "Then just set $key_publishable and $key_secret in index.php and you're good to go."

**Comment by bateller** [comment]
This is due to [short_open_tags](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag). I'd recommend turning this setting on (for any PHP installation really). However I'll make the change to make it easier for those without the setting, or those unsure how to edit their php settings.

More on PHP tags:
https://www.php.net/manual/en/language.basic-syntax.phptags.php

Edit: Resolved with this commit https://github.com/bateller/stripe-terminal-new/commit/0f1d4e4d17c219a338af28eecb3df6e6a73a1223
